language: bash
sudo: false

matrix:
  allow_failures:
  include:

    - os: linux
      dist: bionic
      env: PATH=/usr/bin:/bin:./:/usr/local/bin
      script:
        - openssl version
        - shellcheck --version
        - bash -c 'export SHELLCHECK_OPTS="-S warning -e SC2006"; shopt -s globstar; shellcheck **/*.sh easyrsa3/easyrsa'
        - sh op_test.sh -vv
        - sh -c 'export VERBOSE=1;  cd easyrsa3; easyrsa --batch; ./easyrsa show-ca'

    - os: osx
      osx_image: xcode10.1
      script:
        - openssl version
        - sh op_test.sh -vv
        - sh -c 'export VERBOSE=1;  cd easyrsa3; ./easyrsa --batch; ./easyrsa show-ca'

