language: bash
sudo: false

matrix:
  include:

    - os: linux
      dist: bionic
      env: PATH=/usr/bin:/bin:./:/usr/local/bin
      script:
        - openssl version
        - shellcheck --version
        - bash -c 'export SHELLCHECK_OPTS="-S warning -e SC2006"; shopt -s globstar; shellcheck **/*.sh easyrsa3/easyrsa'
        - sh op_test.sh -vv
        - sh -c 'export VERBOSE=1;  cd easyrsa3; easyrsa --batch upgrade pki; ./easyrsa --batch show-ca'

    - os: osx
      osx_image: xcode10.1
      script:
        - openssl version
        - sh op_test.sh -vv
        - sh -c 'export VERBOSE=1;  cd easyrsa3; ./easyrsa --batch upgrade pki; ./easyrsa --batch show-ca'

    - os: linux
      allow_failures: true
      dist: xenial
      env: PATH=/usr/bin:/bin:./:/usr/local/bin
      script:
        - openssl version
        - shellcheck --version
        - bash -c 'export SHELLCHECK_OPTS="-S warning -e SC2006"; shopt -s globstar; shellcheck **/*.sh easyrsa3/easyrsa'
        - sh op_test.sh -vv
        - sh -c 'rm -f ./easyrsa3/vars.bat'
        - sh -c '[ -f ./easyrsa3/vars.222 ] && mv ./easyrsa3/vars.222 ./easyrsa3/vars'
        - sh -c 'export VERBOSE=1;  cd easyrsa3; easyrsa --batch upgrade pki; ./easyrsa --batch show-ca'

