language: bash
sudo: false

matrix:
  allow_failures:
  include:

    - os: linux
      dist: bionic
      env: PATH=/usr/bin:/bin:./:/usr/local/bin
      script:
        - openssl version
        - shellcheck --version
        - bash -c 'export SHELLCHECK_OPTS="-S warning -e SC2006"; shopt -s globstar; shellcheck **/*.sh easyrsa3/easyrsa'
        - sh -c '[ -f ./easyrsa3/vars.bat ] && mv ./easyrsa3/vars.bat ./easyrsa3/vars.bat.temp'
        - sh op_test.sh -vv
        - sh -c '[ -f ./easyrsa3/vars.bat.temp ] && mv ./easyrsa3/vars.bat.temp ./easyrsa3/vars.bat'
        - sh -c 'export VERBOSE=1;  cd easyrsa3; easyrsa --batch; ./easyrsa --batch show-ca'

    - os: osx
      osx_image: xcode10.1
      script:
        - openssl version
        - sh -c '[ -f ./easyrsa3/vars.bat ] && mv ./easyrsa3/vars.bat ./easyrsa3/vars.bat.temp'
        - sh op_test.sh -vv
        - sh -c '[ -f ./easyrsa3/vars.bat.temp ] && mv ./easyrsa3/vars.bat.temp ./easyrsa3/vars.bat'
        - sh -c 'export VERBOSE=1;  cd easyrsa3; ./easyrsa --batch; ./easyrsa --batch show-ca'

